require 'resource_full/core_extensions/exception'
require 'resource_full/core_extensions/hash'
require 'resource_full/dispatch'
require 'resource_full/query'
require 'resource_full/render'
require 'resource_full/retrieve'
require 'resource_full/version'
require 'resource_full/base'

require 'resource_full/controllers/resources_controller'
require 'resource_full/controllers/routes_controller'
require 'resource_full/core_extensions/api'
